force-app/main/default/objects/Hidden_Divergence_Trade__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hidden_Divergence_Trade__c/fields/Stop_Loss_Price__c.field-meta.xml
<CustomField>
    <fullName>Stop_Loss_Price__c</fullName>
    <label>Stop Loss Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hidden_Divergence_Trade__c/fields/Symbol__c.field-meta.xml
<CustomField>
    <fullName>Symbol__c</fullName>
    <label>Symbol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Symbols</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hidden_Divergence_Trade__c/fields/Take_Profit_Price__c.field-meta.xml
<CustomField>
    <fullName>Take_Profit_Price__c</fullName>
    <label>Take Profit Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DivergenceTradesDataController.cls
public class DivergenceTradesDataController {
    

    @AuraEnabled (cacheable=true)
    public static List<Hidden_Divergence_Trade__c> getAllDivergenceTradesOpen(){
        return [SELECT Id, Name, Open_Price__c, Stage__c, Symbol__c, Stop_Loss_Price__c, Take_Profit_Price__c, CreatedDate, Profit__c, Close_Date_Time__c
                FROM Hidden_Divergence_Trade__c 
                WHERE Stage__c = 'O'
                ORDER BY CreatedDate ASC];       
    }

    @AuraEnabled (cacheable=true)
    public static List<Hidden_Divergence_Trade__c> getAllDivergenceTrades(){
        return [SELECT Id, Name, Open_Price__c, Stage__c, Symbol__c, Stop_Loss_Price__c, Take_Profit_Price__c, CreatedDate, Profit__c, Close_Date_Time__c
                FROM Hidden_Divergence_Trade__c];       
    }

}