force-app/main/default/objects/Currency__c/Currency__c.object-meta.xml
<CustomObject>
    <description>Object to hold all currency pairs for all markets</description>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Transaction__c/Monthly_Transaction__c.object-meta.xml
<CustomObject>
    <label>Monthly Transaction</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Monthly Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Transaction__c/fields/Balance_On_Close__c.field-meta.xml
<CustomField>
    <fullName>Balance_On_Close__c</fullName>
    <label>Balance On Close</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/Oanda_Trade__x.object-meta.xml
<CustomObject>
    <externalDataSource>Amazon_DynamoDB_EU_West_1</externalDataSource>
    <externalName>Oanda-Trades-Table-1</externalName>
    <label>Oanda Trade</label>
    <pluralLabel>Oanda Trades</pluralLabel>
</CustomObject>

force-app/main/default/objects/Oanda_Trade__x/fields/Balance_On_Close__c.field-meta.xml
<CustomField>
    <fullName>Balance_On_Close__c</fullName>
    <label>Balance On Close</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Close_Comments__c.field-meta.xml
<CustomField>
    <fullName>Close_Comments__c</fullName>
    <externalDeveloperName>closeComments</externalDeveloperName>
    <label>Close Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Close_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Close_Date_Time__c</fullName>
    <label>Close Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Close_URL__c.field-meta.xml
<CustomField>
    <fullName>Close_URL__c</fullName>
    <externalDeveloperName>closeUrl</externalDeveloperName>
    <label>Close URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <externalDeveloperName>currency</externalDeveloperName>
    <label>Currency</label>
    <referenceTo>Currency__c</referenceTo>
    <relationshipLabel>Oanda Trades</relationshipLabel>
    <relationshipName>Oanda_Trades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <externalDeveloperName>OandaId</externalDeveloperName>
    <label>Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Monthly_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <externalDeveloperName>monthlyTransaction</externalDeveloperName>
    <label>Monthly Transaction</label>
    <referenceTo>Monthly_Transaction__c</referenceTo>
    <relationshipLabel>Oanda Trades</relationshipLabel>
    <relationshipName>Oanda_Trades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Oanda_Id__c.field-meta.xml
<CustomField>
    <fullName>Oanda_Id__c</fullName>
    <externalDeveloperName>oanda-trade-id</externalDeveloperName>
    <label>Oanda Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Open_Comments__c.field-meta.xml
<CustomField>
    <fullName>Open_Comments__c</fullName>
    <externalDeveloperName>openComments</externalDeveloperName>
    <label>Open Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Open_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Open_Date_Time__c</fullName>
    <externalDeveloperName>openDateTime</externalDeveloperName>
    <label>Open Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Open_URL__c.field-meta.xml
<CustomField>
    <fullName>Open_URL__c</fullName>
    <externalDeveloperName>openUrl</externalDeveloperName>
    <label>Open URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <externalDeveloperName>outcome</externalDeveloperName>
    <label>Outcome</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Profit_Loss__c.field-meta.xml
<CustomField>
    <fullName>Profit_Loss__c</fullName>
    <externalDeveloperName>profit_loss</externalDeveloperName>
    <label>Profit Loss</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Profit_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Profit_Percentage__c</fullName>
    <externalDeveloperName>profitPercentage</externalDeveloperName>
    <label>Profit Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Second_Screenshot__c.field-meta.xml
<CustomField>
    <fullName>Second_Screenshot__c</fullName>
    <externalDeveloperName>secondScreenshot</externalDeveloperName>
    <label>Second Screenshot</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/fields/Side__c.field-meta.xml
<CustomField>
    <fullName>Side__c</fullName>
    <externalDeveloperName>side</externalDeveloperName>
    <label>Side</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/SR_Hedge__c.object-meta.xml
<CustomObject>
    <label>Hedge Trade</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>SR Hedge</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hedge Trades</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SR_Hedge__c/fields/Close_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Close_Date_Time__c</fullName>
    <label>Close Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Close_Screenshot__c.field-meta.xml
<CustomField>
    <fullName>Close_Screenshot__c</fullName>
    <label>Close Screenshot</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Closing_Comments__c.field-meta.xml
<CustomField>
    <fullName>Closing_Comments__c</fullName>
    <label>Closing Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Currency</label>
    <referenceTo>Currency__c</referenceTo>
    <relationshipLabel>Hedge Trades</relationshipLabel>
    <relationshipName>Hedge_Trades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Final_Profit__c.field-meta.xml
<CustomField>
    <fullName>Final_Profit__c</fullName>
    <formula>if(  Number_of_Partial_Closes__c = 0,  X1st_Trade_Profit__c ,  Partials_Profit_Sum__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Oanda_Trade_ID__c.field-meta.xml
<CustomField>
    <fullName>Oanda_Trade_ID__c</fullName>
    <externalId>true</externalId>
    <label>Oanda Trade ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/OandaAccIdPlusTradeId__c.field-meta.xml
<CustomField>
    <fullName>OandaAccIdPlusTradeId__c</fullName>
    <externalId>true</externalId>
    <label>OandaAccIdPlusTradeId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Open_Comments__c.field-meta.xml
<CustomField>
    <fullName>Open_Comments__c</fullName>
    <label>Open Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Open_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Open_Date_Time__c</fullName>
    <label>Open Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Open_Screenshot__c.field-meta.xml
<CustomField>
    <fullName>Open_Screenshot__c</fullName>
    <label>Open Screenshot</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>Outcome of the trade if TP or SL hit</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SL Hit</fullName>
            </value>
            <value>
                <fullName>TP Hit</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Profit_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Profit_Percentage__c</fullName>
    <formula>Final_Profit__c /  Balance_On_Close__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profit Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Second_SS__c.field-meta.xml
<CustomField>
    <fullName>Second_SS__c</fullName>
    <label>Second SS</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Side__c.field-meta.xml
<CustomField>
    <fullName>Side__c</fullName>
    <label>Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Side</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/OandaTradeService.cls
public without sharing class OandaTradeService {
    @AuraEnabled(Cacheable=true)
    public static Oanda_Trade__x getOandaTradeImageUrls(Id recordId) {
        return [
            SELECT Open_URL__c, Close_URL__c, Second_Screenshot__c
            FROM Oanda_Trade__x
            WHERE Id = :recordId 
            LIMIT 1
        ];
    }

    public static List<Oanda_Trade__x> createExternalRecordsFromSrHedge(List<SR_Hedge__c> listOfTrades, Monthly_Transaction__c mT) {
        List<Oanda_Trade__x> listOfArchives = new List<Oanda_Trade__x>();

        for (SR_Hedge__c trade : listOfTrades) {
            Oanda_Trade__x archive = new Oanda_Trade__x();
            archive.Balance_On_Close__c = trade.Balance_On_Close__c;
            archive.Close_Comments__c = trade.Closing_Comments__c;
            archive.Close_Date_Time__c = trade.Close_Date_Time__c;
            archive.Index__c = trade.OandaAccIdPlusTradeId__c;
            archive.Close_URL__c = trade.Close_Screenshot__c;
            archive.Currency__c = trade.Currency__c;
            archive.Monthly_Transaction__c = mT.Id;
            archive.Name__c = trade.Name;
            archive.Oanda_ID__c = trade.Oanda_Trade_ID__c;
            archive.Open_Comments__c =  trade.Open_Comments__c;
            archive.Open_Date_Time__c = trade.Open_Date_Time__c;
            archive.Open_URL__c = trade.Open_Screenshot__c;
            archive.Profit_Loss__c = trade.Final_Profit__c;
            archive.Profit_Percentage__c = trade.Profit_Percentage__c;
            archive.Side__c = trade.Side__c;
            archive.Outcome__c = trade.Outcome__c;
            archive.Second_Screenshot__c = trade.Second_SS__c;

            listOfArchives.add(archive);
        }

        return listOfArchives;
    }

    public static void insertTradesBatch(List<Oanda_Trade__x> listOfArchives) {
        if (!listOfArchives.isEmpty()) {
            BatchInsertDynamo batchInsert = new BatchInsertDynamo(listOfArchives);

            Database.executeBatch(batchInsert, 10);
        }
    }
}