force-app/main/default/objects/Currency__c/Currency__c.object-meta.xml
<CustomObject>
    <description>Object to hold all currency pairs for all markets</description>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SR_Hedge__c/SR_Hedge__c.object-meta.xml
<CustomObject>
    <label>Hedge Trade</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>SR Hedge</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hedge Trades</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SR_Hedge__c/fields/Close_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Close_Date_Time__c</fullName>
    <label>Close Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Close_Screenshot__c.field-meta.xml
<CustomField>
    <fullName>Close_Screenshot__c</fullName>
    <label>Close Screenshot</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Closing_Comments__c.field-meta.xml
<CustomField>
    <fullName>Closing_Comments__c</fullName>
    <label>Closing Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Currency</label>
    <referenceTo>Currency__c</referenceTo>
    <relationshipLabel>Hedge Trades</relationshipLabel>
    <relationshipName>Hedge_Trades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Final_Profit__c.field-meta.xml
<CustomField>
    <fullName>Final_Profit__c</fullName>
    <formula>if(  Number_of_Partial_Closes__c = 0,  X1st_Trade_Profit__c ,  Partials_Profit_Sum__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Oanda_Trade_ID__c.field-meta.xml
<CustomField>
    <fullName>Oanda_Trade_ID__c</fullName>
    <externalId>true</externalId>
    <label>Oanda Trade ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/OandaAccIdPlusTradeId__c.field-meta.xml
<CustomField>
    <fullName>OandaAccIdPlusTradeId__c</fullName>
    <externalId>true</externalId>
    <label>OandaAccIdPlusTradeId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Open_Comments__c.field-meta.xml
<CustomField>
    <fullName>Open_Comments__c</fullName>
    <label>Open Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Open_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Open_Date_Time__c</fullName>
    <label>Open Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Open_Screenshot__c.field-meta.xml
<CustomField>
    <fullName>Open_Screenshot__c</fullName>
    <label>Open Screenshot</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>Outcome of the trade if TP or SL hit</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SL Hit</fullName>
            </value>
            <value>
                <fullName>TP Hit</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Profit_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Profit_Percentage__c</fullName>
    <formula>Final_Profit__c /  Balance_On_Close__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profit Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Second_SS__c.field-meta.xml
<CustomField>
    <fullName>Second_SS__c</fullName>
    <label>Second SS</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Side__c.field-meta.xml
<CustomField>
    <fullName>Side__c</fullName>
    <label>Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Side</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SrHedgeTradesService.cls
public with sharing class SrHedgeTradesService {
    public static List<SR_Hedge__C> getSrHedgeTradesWithStartAndEndDate (Datetime startDate, Datetime endDate) {
        endDate = DateTime.newInstanceGmt(endDate.year(), endDate.month(), endDate.day(), 23, 59, 59);
        
        System.debug(String.valueOf(startDate) + String.valueOf(endDate));
        
        List<SR_Hedge__c> listTrades = [Select id, Side__c, Profit_Percentage__c, Open_Screenshot__c,
                                        Open_Date_Time__c, Oanda_Trade_ID__c, Currency__c, Open_Comments__c,
                                        Closing_Comments__c, Close_Screenshot__c, Balance_On_Close__c, name,
                                        Final_Profit__c, Close_Date_Time__c, Outcome__c, OandaAccIdPlusTradeId__c, Second_SS__c
            FROM sr_hedge__c
            WHERE Close_Date_Time__c >= :startDate AND Close_Date_Time__c <= :endDate];

        return listTrades;

    }

    public static void deleteSrHedgeTrades(List<SR_Hedge__c> tradesToDelete) {
        try {
            System.debug('DELETE ' + tradesToDelete);

            //delete tradesToDelete;
        } catch (Exception ex) {
            System.debug('Error deleting trades');
        }
    }
}