force-app/main/default/objects/Currency__c/Currency__c.object-meta.xml
<CustomObject>
    <description>Object to hold all currency pairs for all markets</description>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Transaction__c/Monthly_Transaction__c.object-meta.xml
<CustomObject>
    <label>Monthly Transaction</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Monthly Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Transaction__c/fields/Balance_On_Close__c.field-meta.xml
<CustomField>
    <fullName>Balance_On_Close__c</fullName>
    <label>Balance On Close</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monthly_Transaction__c/fields/Number_Of_Trades__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Trades__c</fullName>
    <label>Number Of Trades</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Transaction__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <label>Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Transaction__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Primary_Trade_Link__c/fields/Child_SR_Hedge__c.field-meta.xml
<CustomField>
    <fullName>Child_SR_Hedge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child SR Hedge</label>
    <referenceTo>SR_Hedge__c</referenceTo>
    <relationshipLabel>Primary Trade Link</relationshipLabel>
    <relationshipName>Primary_Trade_Links_Child</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Trade_Link__c/fields/Primary_SR_Hedge__c.field-meta.xml
<CustomField>
    <fullName>Primary_SR_Hedge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary SR Hedge</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SR_Hedge__c.Symbol__c</field>
            <operation>equals</operation>
            <valueField>SR_Hedge__c.Symbol__c</valueField>
        </filterItems>
        <filterItems>
            <field>SR_Hedge__c.Primary_Trade__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SR_Hedge__c</referenceTo>
    <relationshipLabel>Primary Trade Links (Child Trades)</relationshipLabel>
    <relationshipName>Primary_Trade_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/SR_Hedge__c.object-meta.xml
<CustomObject>
    <label>Hedge Trade</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>SR Hedge</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hedge Trades</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SR_Hedge__c/fields/Close_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Close_Date_Time__c</fullName>
    <label>Close Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Close_Screenshot__c.field-meta.xml
<CustomField>
    <fullName>Close_Screenshot__c</fullName>
    <label>Close Screenshot</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Closing_Comments__c.field-meta.xml
<CustomField>
    <fullName>Closing_Comments__c</fullName>
    <label>Closing Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Currency</label>
    <referenceTo>Currency__c</referenceTo>
    <relationshipLabel>Hedge Trades</relationshipLabel>
    <relationshipName>Hedge_Trades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Final_Profit__c.field-meta.xml
<CustomField>
    <fullName>Final_Profit__c</fullName>
    <formula>if(  Number_of_Partial_Closes__c = 0,  X1st_Trade_Profit__c ,  Partials_Profit_Sum__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Oanda_Trade_ID__c.field-meta.xml
<CustomField>
    <fullName>Oanda_Trade_ID__c</fullName>
    <externalId>true</externalId>
    <label>Oanda Trade ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Open_Comments__c.field-meta.xml
<CustomField>
    <fullName>Open_Comments__c</fullName>
    <label>Open Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Open_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Open_Date_Time__c</fullName>
    <label>Open Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Open_Screenshot__c.field-meta.xml
<CustomField>
    <fullName>Open_Screenshot__c</fullName>
    <label>Open Screenshot</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>Outcome of the trade if TP or SL hit</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SL Hit</fullName>
            </value>
            <value>
                <fullName>TP Hit</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Profit_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Profit_Percentage__c</fullName>
    <formula>Final_Profit__c /  Balance_On_Close__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profit Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Side__c.field-meta.xml
<CustomField>
    <fullName>Side__c</fullName>
    <label>Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Side</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade_Archive__b/Trade_Archive__b.object-meta.xml
<CustomObject>
    <label>Trade Archive</label>
    <pluralLabel>Trade Archives</pluralLabel>
</CustomObject>

force-app/main/default/objects/Trade_Archive__b/fields/Balance_On_Close__c.field-meta.xml
<CustomField>
    <fullName>Balance_On_Close__c</fullName>
    <label>Balance On Close</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade_Archive__b/fields/Close_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Close_Date_Time__c</fullName>
    <label>Close Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade_Archive__b/fields/Close_URL__c.field-meta.xml
<CustomField>
    <fullName>Close_URL__c</fullName>
    <label>Close URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Trade_Archive__b/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <referenceTo>Currency__c</referenceTo>
    <relationshipLabel>Trade Archives</relationshipLabel>
    <relationshipName>Trade_Archive</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trade_Archive__b/fields/Monthly_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Transaction__c</fullName>
    <label>Monthly Transaction</label>
    <referenceTo>Monthly_Transaction__c</referenceTo>
    <relationshipLabel>Trade Archives</relationshipLabel>
    <relationshipName>Trade_Archive</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trade_Archive__b/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trade_Archive__b/fields/Oanda_ID__c.field-meta.xml
<CustomField>
    <fullName>Oanda_ID__c</fullName>
    <label>Oanda ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trade_Archive__b/fields/Open_and_Close_Comments__c.field-meta.xml
<CustomField>
    <fullName>Open_and_Close_Comments__c</fullName>
    <label>Open and Close Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trade_Archive__b/fields/Open_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Open_Date_Time__c</fullName>
    <label>Open Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade_Archive__b/fields/Open_URL__c.field-meta.xml
<CustomField>
    <fullName>Open_URL__c</fullName>
    <label>Open URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Trade_Archive__b/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trade_Archive__b/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <label>Profit (£)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade_Archive__b/fields/Profit_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Profit_Percentage__c</fullName>
    <label>Profit Percentage (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade_Archive__b/fields/Side__c.field-meta.xml
<CustomField>
    <fullName>Side__c</fullName>
    <label>Side</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MonthlySrToBigObjectsConvert.cls
public with sharing class MonthlySrToBigObjectsConvert {

    //MonthlySrToBigObjectsConvert.convertRecordsToBigObjects('a097Q000004BFiSQAW');
    
    public static void convertRecordsToBigObjects(Id recordId) {
        // Get Monthly Transaction trade
        Monthly_Transaction__c mT = getMonthlyTransaction(recordId);

        // Get SR Trades that are within threshold
        List<SR_Hedge__c> listTrades = getSrHedgeTrades(mT.Start_Date__c, mT.End_Date__c);
        System.debug(listTrades);

        // Create new BO records
        List<Trade_Archive__b> tradesArchives = createTradeArchives(listTrades, mT);

        // Insert Records
        Boolean insertResult = insertArchives(tradesArchives);
        
        if (!insertResult) { return; }

        // Update monthly transaction
        Boolean updateResult = updateMonthlyTransaction(tradesArchives, mT);

        // Delete primary links
        // Select primary links where the parent or child is equal to trade Id
        deletePrimaryLinks(listTrades);

        // Delete Records
        deleteSrHedgeTrades(listTrades);

    }

    public static Monthly_Transaction__C getMonthlyTransaction(Id recordId) {
        Monthly_Transaction__c mt = [Select Id, Start_Date__c, End_Date__c FROM Monthly_Transaction__c WHERE Id = :recordId];

        return mt;
    } 
    
    public static List<SR_Hedge__C> getSrHedgeTrades (Datetime startDate, Datetime endDate) {
        endDate = DateTime.newInstanceGmt(endDate.year(), endDate.month(), endDate.day(), 23, 59, 59);
        
        System.debug(String.valueOf(startDate) + String.valueOf(endDate));
        
        List<SR_Hedge__c> listTrades = [Select id, Side__c, Profit_Percentage__c, Open_Screenshot__c,
                                        Open_Date_Time__c, Oanda_Trade_ID__c, Currency__c, Open_Comments__c,
                                        Closing_Comments__c, Close_Screenshot__c, Balance_On_Close__c, name,
                                        Final_Profit__c, Close_Date_Time__c, Outcome__c
            FROM sr_hedge__c
            WHERE Close_Date_Time__c >= :startDate AND Close_Date_Time__c <= :endDate];

        return listTrades;

    }

    public static List<Trade_Archive__b> createTradeArchives(List<SR_Hedge__c> listOfTrades, Monthly_Transaction__c mT) {
        List<Trade_Archive__b> listOfArchives = new List<Trade_Archive__b>();

        for (SR_Hedge__c trade : listOfTrades) {
            Trade_Archive__b archive = new Trade_Archive__b();
            archive.Balance_On_Close__c = trade.Balance_On_Close__c;
            archive.Close_Date_Time__c = trade.Close_Date_Time__c;
            archive.Close_URL__c = trade.Close_Screenshot__c;
            archive.Currency__c = trade.Currency__c;
            archive.Monthly_Transaction__c = mT.Id;
            archive.Name__c = trade.Name;
            archive.Oanda_ID__c = String.valueOf(trade.Oanda_Trade_ID__c);
            archive.Open_and_Close_Comments__c = 'Open : ' + trade.Open_Comments__c + ' | Close : ' + trade.Closing_Comments__c;
            archive.Open_Date_Time__c = trade.Open_Date_Time__c;
            archive.Open_URL__c = trade.Open_Screenshot__c;
            archive.Profit__c = trade.Final_Profit__c;
            archive.Profit_Percentage__c = trade.Profit_Percentage__c;
            archive.Side__c = trade.Side__c;
            archive.Outcome__c = trade.Outcome__c;

            listOfArchives.add(archive);
        }

        return listOfArchives;
    }

    public static Boolean insertArchives(List<Trade_Archive__b> listOfArchives) {
        if (!listOfArchives.isEmpty()) {
            try {
                database.insertImmediate(listOfArchives);
                System.debug(listOfArchives);
                System.debug(listOfArchives.size());
                return true;
            } catch (Exception ex) {
                return false;
            }
        }
        return false;
    }

    public static Boolean updateMonthlyTransaction(List<Trade_Archive__b> listArchives, Monthly_Transaction__c mT) {
        Decimal totalProfit = 0;
        //Get closing balance
        Decimal closingBalance = 0;
        Datetime latestCloseDate = Datetime.newInstance(2000, 01, 01);
        Integer numberOfTrades = 0;

        for (Trade_Archive__b trade : listArchives) {
            Datetime tradeCloseDate = trade.Close_Date_Time__c;
            numberOfTrades ++;
        
            if (tradeCloseDate != null && tradeCloseDate > latestCloseDate) {
                latestCloseDate = tradeCloseDate;
                closingBalance = trade.Balance_On_Close__c;
            }

            system.debug(trade.Profit__c);
            totalProfit += trade.Profit__c;

        }

        mt.Number_Of_Trades__c = numberOfTrades;
        mt.Balance_On_Close__c = closingBalance;
        mt.Profit__c = totalProfit;

        try {
            update mT;
        } catch (Exception ex) {
            System.debug('Error updating monthly transaction');
        }

        return true;
    }

    public static void deletePrimaryLinks(List<SR_Hedge__c> listOfTrades) {
        Set<Id> tradeIds = new Set<Id>();

        for (SR_Hedge__c trade : listOfTrades) {
            tradeIds.add(trade.Id);
        }

        List<Primary_Trade_Link__c> primaryLinksToDelete = [SELECT Id
            FROM Primary_Trade_Link__c
            WHERE Primary_SR_Hedge__c IN :tradeIds OR Child_SR_Hedge__c IN :tradeIds];

        if (!primaryLinksToDelete.isEmpty()) {
            try {
                //System.debug('DELETE ' + primaryLinksToDelete);

                delete primaryLinksToDelete;
            } catch (Exception ex) {
                System.debug('Error deleting links');
            }
        }

    }

    public static void deleteSrHedgeTrades(List<SR_Hedge__c> tradesToDelete) {
        try {
            System.debug('DELETE ' + tradesToDelete);

            delete tradesToDelete;
        } catch (Exception ex) {
            System.debug('Error deleting trades');
        }
    }
}