force-app/main/default/objects/Currency__c/Currency__c.object-meta.xml
<CustomObject>
    <description>Object to hold all currency pairs for all markets</description>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Trade_Link__c/fields/Child_SR_Hedge__c.field-meta.xml
<CustomField>
    <fullName>Child_SR_Hedge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child SR Hedge</label>
    <referenceTo>SR_Hedge__c</referenceTo>
    <relationshipLabel>Primary Trade Link</relationshipLabel>
    <relationshipName>Primary_Trade_Links_Child</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Trade_Link__c/fields/Primary_SR_Hedge__c.field-meta.xml
<CustomField>
    <fullName>Primary_SR_Hedge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary SR Hedge</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SR_Hedge__c.Symbol__c</field>
            <operation>equals</operation>
            <valueField>SR_Hedge__c.Symbol__c</valueField>
        </filterItems>
        <filterItems>
            <field>SR_Hedge__c.Primary_Trade__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SR_Hedge__c</referenceTo>
    <relationshipLabel>Primary Trade Links (Child Trades)</relationshipLabel>
    <relationshipName>Primary_Trade_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/SR_Hedge__c.object-meta.xml
<CustomObject>
    <label>Hedge Trade</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>SR Hedge</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hedge Trades</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SR_Hedge__c/fields/Close_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Close_Date_Time__c</fullName>
    <label>Close Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Currency</label>
    <referenceTo>Currency__c</referenceTo>
    <relationshipLabel>Hedge Trades</relationshipLabel>
    <relationshipName>Hedge_Trades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Primary_Trade__c.field-meta.xml
<CustomField>
    <fullName>Primary_Trade__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Trade</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>if (    ISBLANK(Final_Close_Date__c ), &apos;Open&apos;, &apos;Closed&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HedgeTradeHandler.cls
public class HedgeTradeHandler {
    
    
    public void beforeInsert(List<SR_Hedge__c> trades, Boolean isBefore, Boolean isAfter) {
        updatePrimaryTradeField(trades, isBefore,isAfter);
    }
    
    public void handleProfits(List<SR_Hedge__c> trades) {
        System.debug('handle profits, api call');
        for (SR_Hedge__c trade : trades) {
            system.debug(trade.Close_Date_Time__c.dateGMT() + '/' + trade.Close_Date_Time__c.getTime());
            
            FetchExchangeRateAPI.convertAmount();
        }
    }
    
    public void updatePrimaryTradeField(List<SR_Hedge__c> trades, Boolean isBefore, Boolean isAfter) {
        Set<String> currencies = new Set<String>();
        for (SR_Hedge__c trade : trades) {
            currencies.add(trade.Currency__c);
        }
        
        // Query for all open trades with currencies in the set
        Map<String, List<SR_Hedge__c>> openTradesByCurrency = new Map<String, List<SR_Hedge__c>>();
        for (SR_Hedge__c openTrade : [
            SELECT Id, Currency__c, Status__c 
            FROM SR_Hedge__c 
            WHERE Currency__c IN :currencies AND Status__c = 'Open'
        ]) {
            if (!openTradesByCurrency.containsKey(openTrade.Currency__c)) {
                openTradesByCurrency.put(openTrade.Currency__c, new List<SR_Hedge__c>());
            }
            openTradesByCurrency.get(openTrade.Currency__c).add(openTrade);
        }
        
        // Query for the most recent primary trade for each currency
        Map<String, SR_Hedge__c> mostRecentPrimaryByCurrency = new Map<String, SR_Hedge__c>();
        for (SR_Hedge__c primaryTrade : [
            SELECT Id, Currency__c, Name, Primary_Trade__c 
            FROM SR_Hedge__c 
            WHERE Primary_Trade__c = true AND Currency__c IN :currencies 
            ORDER BY Name DESC
        ]) {
            if (!mostRecentPrimaryByCurrency.containsKey(primaryTrade.Currency__c)) {
                mostRecentPrimaryByCurrency.put(primaryTrade.Currency__c, primaryTrade);
            }
        }
        
        // Update the trigger records based on the query results
        List<SR_Hedge__c> tradesToUpdate = new List<SR_Hedge__c>();
        List<Primary_Trade_Link__c> linksToInsert = new List<Primary_Trade_Link__c>();
        for (SR_Hedge__c trade : trades) {
            if (!openTradesByCurrency.containsKey(trade.Currency__c)) {
                if (isBefore) {
                    trade.Primary_Trade__c = true;
                    tradesToUpdate.add(trade);
                }
            } else {
                if (isAfter) {
                    SR_Hedge__c mostRecentPrimary = mostRecentPrimaryByCurrency.get(trade.Currency__c);
                    if (mostRecentPrimary != null && mostRecentPrimary.Id != trade.Id) {
                        Primary_Trade_Link__c newLink = new Primary_Trade_Link__c(
                            Primary_SR_Hedge__c = mostRecentPrimary.Id,
                            Child_SR_Hedge__c = trade.Id
                        );
                        linksToInsert.add(newLink);
                    }
                }
            }
        }
        
        /*if (tradesToUpdate.size() > 0) {
            update tradesToUpdate;
        }*/
        
        if (linksToInsert.size() > 0) {
            insert linksToInsert;
        }
    }

}