force-app/main/default/objects/Currency__c/Currency__c.object-meta.xml
<CustomObject>
    <description>Object to hold all currency pairs for all markets</description>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SR_Hedge__c/SR_Hedge__c.object-meta.xml
<CustomObject>
    <label>Hedge Trade</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>SR Hedge</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hedge Trades</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SR_Hedge__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Currency</label>
    <referenceTo>Currency__c</referenceTo>
    <relationshipLabel>Hedge Trades</relationshipLabel>
    <relationshipName>Hedge_Trades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Final_Units_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Final_Units_Remaining__c</fullName>
    <formula>IF ( 
  Number_of_Partial_Closes__c &gt; 0,
  Units_Remaining__c,
  IF ( NOT(ISBLANK(Close_Date_Time__c)),
    0,
    X1st_Trade_Units__c 
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Units Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>if (    ISBLANK(Final_Close_Date__c ), &apos;Open&apos;, &apos;Closed&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SupportResistanceTradesDataController.cls
public with sharing class SupportResistanceTradesDataController {
    public SupportResistanceTradesDataController() {

    }

    @AuraEnabled (cacheable=true)
    public static List<SR_Hedge__c> getAllTechnicalAnalysisTradesOpen(){
        return [SELECT Id, Name, Currency__r.Name, Status__c, Final_Units_Remaining__c
                FROM SR_Hedge__c 
                WHERE Status__c = 'Open' AND CreatedByID = :UserInfo.getUserId()
                ORDER BY Currency__r.Name ASC];       
    }

    @AuraEnabled (cacheable=true)
    public static List<SR_Hedge__c> getAllTechnicalAnalysisTrades(){
        return [SELECT Id, Name, Currency__r.Name, Status__c, Final_Units_Remaining__c
                FROM SR_Hedge__c];   
    }
}