force-app/main/default/objects/Monthly_Transaction__c/Monthly_Transaction__c.object-meta.xml
<CustomObject>
    <label>Monthly Transaction</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Monthly Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monthly_Transaction__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Oanda_Trade__x/Oanda_Trade__x.object-meta.xml
<CustomObject>
    <externalDataSource>Amazon_DynamoDB_EU_West_1</externalDataSource>
    <externalName>Oanda-Trades-Table-1</externalName>
    <label>Oanda Trade</label>
    <pluralLabel>Oanda Trades</pluralLabel>
</CustomObject>

force-app/main/default/objects/Oanda_Trade__x/fields/Monthly_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <externalDeveloperName>monthlyTransaction</externalDeveloperName>
    <label>Monthly Transaction</label>
    <referenceTo>Monthly_Transaction__c</referenceTo>
    <relationshipLabel>Oanda Trades</relationshipLabel>
    <relationshipName>Oanda_Trades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/SR_Hedge__c.object-meta.xml
<CustomObject>
    <label>Hedge Trade</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>SR Hedge</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hedge Trades</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ConvertMonthlySrHedgeTradesToAwsDynamo.cls
public with sharing class ConvertMonthlySrHedgeTradesToAwsDynamo {
    public static void convertRecordsToExternalRecords(Id recordId) {
        Monthly_Transaction__c mT = MonthlyTransactionService.getMonthlyTransaction(recordId);

        List<SR_Hedge__c> listTrades = SrHedgeTradesService.getSrHedgeTradesWithStartAndEndDate(mT.Start_Date__c, mT.End_Date__c);
        
        List<Oanda_Trade__x> tradesAws = OandaTradeService.createExternalRecordsFromSrHedge(listTrades, mT);
        
        OandaTradeService.insertTradesBatch(tradesAws);

        // Select primary links where the parent or child is equal to trade Id
        PrimaryLinkService.deletePrimaryLinks(listTrades);

        // Delete Records
        SrHedgeTradesService.deleteSrHedgeTrades(listTrades);

        //rollupMonthlyResults(mT.Id);


    }

    public static void rollupMonthlyResults(Id recordId) {

        Map<String, Object> params = new Map<String, Object>();
        params.put('recordId', recordId);

        Flow.Interview.Rollup_Monthly_Transactions rollupFlow = new Flow.Interview.Rollup_Monthly_Transactions(params);
        rollupFlow.start();
    }

}