force-app/main/default/objects/Account/fields/First_Trade__c.field-meta.xml
<CustomField>
    <fullName>First_Trade__c</fullName>
    <label>First Trade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Oanda_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Oanda_Account_Id__c</fullName>
    <label>Oanda Account Id</label>
    <length>63</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Second_SS__c.field-meta.xml
<CustomField>
    <fullName>Second_SS__c</fullName>
    <label>Second SS</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Second_Trade__c.field-meta.xml
<CustomField>
    <fullName>Second_Trade__c</fullName>
    <label>Second Trade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Third_Trade__c.field-meta.xml
<CustomField>
    <fullName>Third_Trade__c</fullName>
    <label>Third Trade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Algo_Trade__c/Algo_Trade__c.object-meta.xml
<CustomObject>
    <label>Algorithmic Trade</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>Algorithmic Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Algorithmic Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Algo_Trade__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <label>Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Algo_Trade__c/fields/Profit_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Profit_Percentage__c</fullName>
    <label>Profit Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Algo_Trade__c/fields/Start_Balance__c.field-meta.xml
<CustomField>
    <fullName>Start_Balance__c</fullName>
    <label>Start Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Algo_Trade__c/fields/Trade_Id__c.field-meta.xml
<CustomField>
    <fullName>Trade_Id__c</fullName>
    <label>Trade Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Algo_Trade__c/fields/Trading_Account__c.field-meta.xml
<CustomField>
    <fullName>Trading_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trading Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Algorithmic Trades</relationshipLabel>
    <relationshipName>Algo_Trades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Algo_Trade__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <label>Unique Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Algorithmic_Trade__x/Algorithmic_Trade__x.object-meta.xml
<CustomObject>
    <externalDataSource>Amazon_DynamoDB_EU_West_1</externalDataSource>
    <externalName>Algorithmic-Trades</externalName>
    <label>Algorithmic Trade</label>
    <pluralLabel>Algorithmic Trades</pluralLabel>
</CustomObject>

force-app/main/default/objects/Algorithmic_Trade__x/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <externalDeveloperName>accountId</externalDeveloperName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Algorithmic Trades</relationshipLabel>
    <relationshipName>Algorithmic_Trades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Algorithmic_Trade__x/fields/Close_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Close_Date_Time__c</fullName>
    <externalDeveloperName>closeDateTime</externalDeveloperName>
    <label>Close Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Algorithmic_Trade__x/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <externalDeveloperName>profit</externalDeveloperName>
    <label>Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Algorithmic_Trade__x/fields/Profit_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Profit_Percentage__c</fullName>
    <externalDeveloperName>profitPercentage</externalDeveloperName>
    <label>Profit Percentage (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Algorithmic_Trade__x/fields/Start_Balance__c.field-meta.xml
<CustomField>
    <fullName>Start_Balance__c</fullName>
    <externalDeveloperName>startBalance</externalDeveloperName>
    <label>Start Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Algorithmic_Trade__x/fields/Trade_Id__c.field-meta.xml
<CustomField>
    <fullName>Trade_Id__c</fullName>
    <externalDeveloperName>tradeId</externalDeveloperName>
    <label>Trade Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Algorithmic_Trade__x/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <externalDeveloperName>index</externalDeveloperName>
    <label>Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trading_Account__c/Trading_Account__c.object-meta.xml
<CustomObject>
    <label>Trading Account</label>
    <nameField>
        <label>Trading Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trading Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trading_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trading Accounts</relationshipLabel>
    <relationshipName>Trading_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RESTResourceTradingViewWebhook.cls
@RestResource(urlMapping='/rr-tradingview/*')
global class RESTResourceTradingViewWebhook {
    @HttpPost
    global static void doPost() {
        System.RestRequest request = RestContext.request;
        String requestBody = request.requestBody.toString();

        String requestURI = request.requestURI;
        System.debug('Request URI: ' + requestURI);

        // Assuming your URL mapping is /rr-tradingview/*
        String[] uriParts = requestURI.split('/');
        String action = uriParts.size() > 2 ? uriParts[2] : '';

        System.debug('TEST REQ | ' + requestBody + ' | ' + action);

        if (action == 'call') {
            // Handle /rr-tradingview/call
            System.debug('MAKE CALL');
            TwilioAPIHandler.makeCall();  // Uncomment and implement this method as needed
        } else if (action == 'signal') {
            // Handle /rr-tradingview/signal
            System.debug('SIGNAL');
            //Callout to make oanda trade  // Uncomment and implement this method as needed
            placeTrade(requestBody);
        }  else if (action == 'signal2') {
            // Handle /rr-tradingview/signal
            System.debug('signal2');
            //Callout to make oanda trade  // Uncomment and implement this method as needed
            placeTrade2(requestBody);
        }


        // If param is /call, make call, if not signal trade
        //

        System.RestResponse response = RestContext.response;

        

    }

    private static void placeTrade2(String strBody) {

        //RESTResponse.OandaTransactionsPage page = (RESTResponse.OandaTransactionsPage) JSON.deserialize(jsonString, RESTResponse.OandaTransactionsPage.class);     


        SignalTrade tradeSignal = (SignalTrade) JSON.deserialize(strBody, SignalTrade.class);

        HttpRequest req = new HttpRequest();
            req.setEndpoint('https://api-fxpractice.oanda.com/v3/accounts/101-004-23424312-001/orders');
            req.setHeader('Authorization', 'Bearer 1f1befaad5d67687ff7e0aa2eb10eac7-d09b57596e582795520209741fc897f8');
            req.setMethod('POST');
            req.setHeader('Content-Type', 'application/json');

        Decimal unitsTrade;
        Decimal trailingStopLoss;

        if (tradeSignal.side == 'buy') {
            unitsTrade = 1000;//tradeSignal.contracts;
        } else {
            unitsTrade = -1000;//-tradeSignal.contracts;
        }

        String jsonBody = '{"order":{"type" : "MARKET","instrument" : "USD_JPY","units" : ' + unitsTrade +
            ',"timeInForce" : "FOK","positionFill" : "DEFAULT"}}';

        req.setBody(jsonBody);

        System.debug('REQ | ' + req + ' BODY ' + jsonBody);

        Account acc = [Select Id, Second_SS__c FROM Account Where Id  ='0017Q00000qPbARQA0'];

        System.debug('HERE ' +acc.Second_SS__c);

        if (acc.Second_SS__c == null) {
            Http http = new Http();
            HTTPResponse res = http.send(req);
    
            if (res.getStatusCode() == 201) {
                // Parse the response to get the trade ID
                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
                Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
                String tradeId = (String) orderFillTransaction.get('id');
    
                acc.Second_SS__c = tradeId;
                update acc;
        
                // Schedule the closure of the trade after 60 seconds
                // String cronExp = System.now().addSeconds(60).format('s m H d M \'?\' yyyy');
                // CloseTradeAfterDelay job = new CloseTradeAfterDelay(tradeId, '101-004-23424312-002');
                // System.schedule('CloseTradeJob' + System.currentTimeMillis(), cronExp, job);
        
                // System.debug('Trade will be closed after 60 seconds, trade ID: ' + tradeId);
            } else {
                System.debug('Failed to place trade: ' + res.getBody());
            }
        } else {
            HTTPResponse res = closeTrade(acc.Second_SS__c, '101-004-23424312-001', '1f1befaad5d67687ff7e0aa2eb10eac7-d09b57596e582795520209741fc897f8');
            acc.Second_SS__c = '';
            update acc;
            
            
            return;
        }

        
    }

    private static HTTPResponse closeTrade(String tradeId, String accountId, String bearerToken) {
        
        String endpoint = 'https://api-fxpractice.oanda.com/v3/accounts/' + accountId + '/trades/' + tradeId + '/close';
    
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpoint);
        req.setHeader('Authorization', 'Bearer ' + bearerToken);
        req.setMethod('PUT');
        req.setHeader('Content-Type', 'application/json');

        Http http = new Http();
        HTTPResponse res = http.send(req);
        System.debug('Close trade response: ' + res.getBody());
        return res;

    }
    
    @future(callout=true)
    private static void placeTradeFuture(String str) {
        placeTrade(str);
    }

    public static void placeTrade(String strBody) {

        //RESTResponse.OandaTransactionsPage page = (RESTResponse.OandaTransactionsPage) JSON.deserialize(jsonString, RESTResponse.OandaTransactionsPage.class);     


        SignalTrade tradeSignal = (SignalTrade) JSON.deserialize(strBody, SignalTrade.class);

        HttpRequest req = new HttpRequest();
            req.setEndpoint('https://api-fxpractice.oanda.com/v3/accounts/101-004-23424312-002/orders');
            req.setHeader('Authorization', 'Bearer 3ca1fa8d639245ae65178cdfda22708e-82f12203086ee753781867a146bde7f0');
            req.setMethod('POST');
            req.setHeader('Content-Type', 'application/json');

        Decimal unitsTrade;
        
        // Check first trade, if it is buy, and buy, then add anotehr buy
        // If it is buy, buy and buy, add trade
        // If the first does not equal the new, then close and open another
        
        Account accFirst = [Select Id, Second_SS__c, First_Trade__c, Second_Trade__c, Third_Trade__c, Oanda_Account_Id__c FROM Account Where Id  ='0017Q00001TwBUCQA3'];
        
        String firstTradeData = accFirst.First_Trade__c;
        String secondTradeData = accFirst.Second_Trade__c;
        String thirdTradeData = accFirst.Third_Trade__c;
		
        
        // if anythign is take profit, close
        if (tradeSignal.comment == 'Take Profit Short' || tradeSignal.comment == 'Take Profit Long') {
            // Close all trades
            HTTPResponse res1;
            HTTPResponse res2;
            HTTPResponse res3;
            
            List<String> firstTradeParts = new List<String>();
            List<String> secondTradeParts = new List<String>();
            List<String> thirdTradeParts = new List<String>();
            
            if (firstTradeData != null) {
                firstTradeParts = firstTradeData.split('-');
                res1 = closeTrade(firstTradeParts[1], '101-004-23424312-002', '3ca1fa8d639245ae65178cdfda22708e-82f12203086ee753781867a146bde7f0');
            }
            
            if (secondTradeData != null) { 
                secondTradeParts = secondTradeData.split('-');
                res2 = closeTrade(secondTradeParts[1], '101-004-23424312-002', '3ca1fa8d639245ae65178cdfda22708e-82f12203086ee753781867a146bde7f0');

            }
                
            if (thirdTradeData != null) {
                thirdTradeParts = thirdTradeData.split('-');
                res3 = closeTrade(thirdTradeParts[1], '101-004-23424312-002', '3ca1fa8d639245ae65178cdfda22708e-82f12203086ee753781867a146bde7f0');

            }
            
            if (firstTradeData != null) {
                //List<String> firstTradeParts = firstTradeData.split('-');
            
                String index = accFirst.Id + '-' + accFirst.Oanda_Account_Id__c + '-' + firstTradeParts[1];
                accFirst.First_Trade__c = '';
                update accFirst;
                
                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res1.getBody());
                Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
                
                String timeStr = String.valueOf(orderFillTransaction.get('time'));
                timeStr = timeStr.substring(0, timeStr.length() - 1);
                timeStr = timeStr.substring(0, timeStr.indexOf('.'));
                timeStr = timeStr.replace('T', ' ');
    
                     
                Datetime endDateTime =  Datetime.valueOf(timeStr);
                //Datetime endDateTime = (Datetime) orderFillTransaction.get('time');
                
                Algo_Trade__c algoTrade = [SELECT Id, Trade_ID__c,
                                                  Close_Date_Time__c, Profit__c,
                                                  Profit_Percentage__c, Start_Balance__c
                                                  FROM Algo_Trade__c WHERE Unique_Id__c = :index];
                Decimal accountBalance = Decimal.valueOf(String.valueOf(orderFillTransaction.get('accountBalance')));
                Decimal profit = Decimal.valueOf(String.valueOf(orderFillTransaction.get('pl')));
                Decimal profitPercentage = (profit / algoTrade.Start_Balance__c) * 100;
                algoTrade.Close_Date_Time__c = endDateTime;
                algoTrade.Profit__c = profit;
                algoTrade.Profit_Percentage__c = profitPercentage;
                
                update algoTrade;

            }
            if (secondTradeData != null) {
            
                String index = accFirst.Id + '-' + accFirst.Oanda_Account_Id__c + '-' + secondTradeParts[1];
                accFirst.Second_Trade__c = '';
                update accFirst;
                
                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res2.getBody());
                Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
                
                String timeStr = String.valueOf(orderFillTransaction.get('time'));
                timeStr = timeStr.substring(0, timeStr.length() - 1);
                timeStr = timeStr.substring(0, timeStr.indexOf('.'));
                timeStr = timeStr.replace('T', ' ');
    
                     
                Datetime endDateTime =  Datetime.valueOf(timeStr);
                //Datetime endDateTime = (Datetime) orderFillTransaction.get('time');
                
                Algo_Trade__c algoTrade = [SELECT Id, Trade_ID__c,
                                                  Close_Date_Time__c, Profit__c,
                                                  Profit_Percentage__c, Start_Balance__c
                                                  FROM Algo_Trade__c WHERE Unique_Id__c = :index];
                Decimal accountBalance = Decimal.valueOf(String.valueOf(orderFillTransaction.get('accountBalance')));
                Decimal profit = Decimal.valueOf(String.valueOf(orderFillTransaction.get('pl')));
                Decimal profitPercentage = (profit / algoTrade.Start_Balance__c) * 100;
                algoTrade.Close_Date_Time__c = endDateTime;
                algoTrade.Profit__c = profit;
                algoTrade.Profit_Percentage__c = profitPercentage;
                
                update algoTrade;
            }
            
            if (thirdTradeData != null) {
            
                String index = accFirst.Id + '-' + accFirst.Oanda_Account_Id__c + '-' + thirdTradeParts[1];
                accFirst.Third_Trade__c = '';
                update accFirst;
                
                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res3.getBody());
                Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
                
                String timeStr = String.valueOf(orderFillTransaction.get('time'));
                timeStr = timeStr.substring(0, timeStr.length() - 1);
                timeStr = timeStr.substring(0, timeStr.indexOf('.'));
                timeStr = timeStr.replace('T', ' ');
    
                     
                Datetime endDateTime =  Datetime.valueOf(timeStr);
                //Datetime endDateTime = (Datetime) orderFillTransaction.get('time');
                
                Algo_Trade__c algoTrade = [SELECT Id, Trade_ID__c,
                                                  Close_Date_Time__c, Profit__c,
                                                  Profit_Percentage__c, Start_Balance__c
                                                  FROM Algo_Trade__c WHERE Unique_Id__c = :index];
                Decimal accountBalance = Decimal.valueOf(String.valueOf(orderFillTransaction.get('accountBalance')));
                Decimal profit = Decimal.valueOf(String.valueOf(orderFillTransaction.get('pl')));
                Decimal profitPercentage = (profit / algoTrade.Start_Balance__c) * 100;
                algoTrade.Close_Date_Time__c = endDateTime;
                algoTrade.Profit__c = profit;
                algoTrade.Profit_Percentage__c = profitPercentage;
                
                update algoTrade;
            }
            
          
            accFirst.First_Trade__c = '';
            accFirst.Second_Trade__c = '';
            accFirst.Third_Trade__c = '';
            update accFirst;
            return;
        }
        
        if (tradeSignal.side == 'buy') {
            unitsTrade = 1;
        } else {
            unitsTrade = -1;
        }
        
        Http http = new Http();

        String jsonBody = '{"order":{"type" : "MARKET","instrument" : "XAU_USD","units" : "' + unitsTrade + '","timeInForce" : "FOK","positionFill" : "DEFAULT"}}';
        
        req.setBody(jsonBody);	
        
        if (firstTradeData != null) {
            List<String> firstTradeParts = firstTradeData.split('-');
            if (firstTradeParts[0] == tradeSignal.side) {	
                
                if (secondTradeData != null) {
                    List<String> secondTradeParts = secondTradeData.split('-');
                    if (secondTradeParts[0] == tradeSignal.side) {
		                        
                        if (thirdTradeData != null) {
                            List<String> thirdTradeParts = thirdTradeData.split('-');
                            if (secondTradeParts[0] != tradeSignal.side) {
                                // Close all and place new
                                HTTPResponse res = closeTrade(firstTradeParts[1], '101-004-23424312-002', '3ca1fa8d639245ae65178cdfda22708e-82f12203086ee753781867a146bde7f0');
                                HTTPResponse res2 = closeTrade(secondTradeParts[1], '101-004-23424312-002', '3ca1fa8d639245ae65178cdfda22708e-82f12203086ee753781867a146bde7f0');

                        
                                String index = accFirst.Id + '-' + accFirst.Oanda_Account_Id__c + '-' + firstTradeParts[1];
                                String index2 = accFirst.Id + '-' + accFirst.Oanda_Account_Id__c + '-' + secondTradeParts[1];

                                accFirst.First_Trade__c = '';
                                accFirst.Second_Trade__c = '';
                                update accFirst;
                                
                                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
                                Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
                                
                                Map<String, Object> responseMap2 = (Map<String, Object>) JSON.deserializeUntyped(res2.getBody());
                                Map<String, Object> orderFillTransaction2 = (Map<String, Object>) responseMap2.get('orderFillTransaction');
                                
                                String timeStr = String.valueOf(orderFillTransaction.get('time'));
                                timeStr = timeStr.substring(0, timeStr.length() - 1);
                                timeStr = timeStr.substring(0, timeStr.indexOf('.'));
                                timeStr = timeStr.replace('T', ' ');
                    
                                String timeStr2 = String.valueOf(orderFillTransaction2.get('time'));
                                timeStr = timeStr2.substring(0, timeStr2.length() - 1);
                                timeStr = timeStr2.substring(0, timeStr2.indexOf('.'));
                                timeStr = timeStr2.replace('T', ' ');
                                     
                                Datetime endDateTime =  Datetime.valueOf(timeStr);
                                Datetime endDateTime2 =  Datetime.valueOf(timeStr2);

                                //Datetime endDateTime = (Datetime) orderFillTransaction.get('time');
                                
                                Algo_Trade__c algoTrade = [SELECT Id, Trade_ID__c,
                                                                  Close_Date_Time__c, Profit__c,
                                                                  Profit_Percentage__c, Start_Balance__c
                                                                  FROM Algo_Trade__c WHERE Unique_Id__c = :index];
                                Decimal accountBalance = Decimal.valueOf(String.valueOf(orderFillTransaction.get('accountBalance')));
               				 	Decimal profit = Decimal.valueOf(String.valueOf(orderFillTransaction.get('pl')));
                                Decimal profitPercentage = (profit / algoTrade.Start_Balance__c) * 100;
                                algoTrade.Close_Date_Time__c = endDateTime;
                                algoTrade.Profit__c = profit;
                                algoTrade.Profit_Percentage__c = profitPercentage;
                                
                                update algoTrade;
                                
                                Algo_Trade__c algoTrade2 = [SELECT Id, Trade_ID__c,
                                                                  Close_Date_Time__c, Profit__c,
                                                                  Profit_Percentage__c, Start_Balance__c
                                                                  FROM Algo_Trade__c WHERE Unique_Id__c = :index2];
                                Decimal accountBalance2 = Decimal.valueOf(String.valueOf(orderFillTransaction2.get('accountBalance')));
                                Decimal profit2 = accountBalance2 - algoTrade2.Start_Balance__c;
                                Decimal profitPercentage2 = (profit2 / algoTrade2.Start_Balance__c) * 100;
                                algoTrade2.Close_Date_Time__c = endDateTime2;
                                algoTrade2.Profit__c = profit2;
                                algoTrade2.Profit_Percentage__c = profitPercentage2;
                                
                                update algoTrade2;
                                                                
                                if (tradeSignal.comment == 'Long' || tradeSignal.comment == 'Short') { 
                                    placeTradeFuture(strBody);
                                    return;
                                }
                                
                            }
                        } else {
                            req.setBody(jsonBody);
            
                            HTTPResponse res = http.send(req);
                            
                            if (res.getStatusCode() == 201) {
                                // Parse the response to get the trade ID
                                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
                                Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
                                String tradeId = (String) orderFillTransaction.get('id');
                                Decimal accountBalance = Decimal.valueOf(String.valueOf(orderFillTransaction.get('accountBalance')));
                                String timeStr = String.valueOf(orderFillTransaction.get('time'));
                                timeStr = timeStr.substring(0, timeStr.length() - 1);
                                timeStr = timeStr.substring(0, timeStr.indexOf('.'));
                                timeStr = timeStr.replace('T', ' ');
                
                                 
                                Datetime startDateTime =  Datetime.valueOf(timeStr);
                                String index = accFirst.Id + '-' + accFirst.Oanda_Account_Id__c + '-' + tradeId;
                    
                                accFirst.Third_Trade__c = tradeSignal.side + '-' + tradeId;
                                update accFirst;
                                
                                Algo_Trade__c tradeInsert = new Algo_Trade__c();
                                tradeInsert.Trading_Account__c = accFirst.Id;
                                tradeInsert.Open_Date_Time__c = startDateTime;
                                tradeInsert.Unique_Id__c = index;
                                tradeInsert.Start_Balance__c = accountBalance;
                                tradeInsert.Trade_Id__c = tradeId;
                                
                                insert tradeInsert;
                            }
                        }
                    } else {
                        // Close 2 and re-buy
                        HTTPResponse res = closeTrade(firstTradeParts[1], '101-004-23424312-002', '3ca1fa8d639245ae65178cdfda22708e-82f12203086ee753781867a146bde7f0');
                        HTTPResponse res2 = closeTrade(secondTradeParts[1], '101-004-23424312-002', '3ca1fa8d639245ae65178cdfda22708e-82f12203086ee753781867a146bde7f0');

                
                        String index = accFirst.Id + '-' + accFirst.Oanda_Account_Id__c + '-' + firstTradeParts[1];
                        String index2 = accFirst.Id + '-' + accFirst.Oanda_Account_Id__c + '-' + secondTradeParts[1];

                        accFirst.First_Trade__c = '';
                        accFirst.Second_Trade__c = '';
                        update accFirst;
                        
                        Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
                        Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
                        
                        Map<String, Object> responseMap2 = (Map<String, Object>) JSON.deserializeUntyped(res2.getBody());
                        Map<String, Object> orderFillTransaction2 = (Map<String, Object>) responseMap2.get('orderFillTransaction');
                        
                        String timeStr = String.valueOf(orderFillTransaction.get('time'));
                        timeStr = timeStr.substring(0, timeStr.length() - 1);
                        timeStr = timeStr.substring(0, timeStr.indexOf('.'));
                        timeStr = timeStr.replace('T', ' ');
            
                        String timeStr2 = String.valueOf(orderFillTransaction2.get('time'));
                        timeStr = timeStr2.substring(0, timeStr2.length() - 1);
                        timeStr = timeStr2.substring(0, timeStr2.indexOf('.'));
                        timeStr = timeStr2.replace('T', ' ');
                             
                        Datetime endDateTime =  Datetime.valueOf(timeStr);
                        Datetime endDateTime2 =  Datetime.valueOf(timeStr2);

                        //Datetime endDateTime = (Datetime) orderFillTransaction.get('time');
                        
                        Algo_Trade__c algoTrade = [SELECT Id, Trade_ID__c,
                                                          Close_Date_Time__c, Profit__c,
                                                          Profit_Percentage__c, Start_Balance__c
                                                          FROM Algo_Trade__c WHERE Unique_Id__c = :index];
                        Decimal accountBalance = Decimal.valueOf(String.valueOf(orderFillTransaction.get('accountBalance')));
                		Decimal profit = Decimal.valueOf(String.valueOf(orderFillTransaction.get('pl')));
                        Decimal profitPercentage = (profit / algoTrade.Start_Balance__c) * 100;
                        algoTrade.Close_Date_Time__c = endDateTime;
                        algoTrade.Profit__c = profit;
                        algoTrade.Profit_Percentage__c = profitPercentage;
                        
                        update algoTrade;
                        
                        Algo_Trade__c algoTrade2 = [SELECT Id, Trade_ID__c,
                                                          Close_Date_Time__c, Profit__c,
                                                          Profit_Percentage__c, Start_Balance__c
                                                          FROM Algo_Trade__c WHERE Unique_Id__c = :index2];
                        Decimal accountBalance2 = Decimal.valueOf(String.valueOf(orderFillTransaction2.get('accountBalance')));
                        Decimal profit2 = accountBalance2 - algoTrade2.Start_Balance__c;
                        Decimal profitPercentage2 = (profit2 / algoTrade2.Start_Balance__c) * 100;
                        algoTrade2.Close_Date_Time__c = endDateTime2;
                        algoTrade2.Profit__c = profit2;
                        algoTrade2.Profit_Percentage__c = profitPercentage2;
                        
                        update algoTrade2;
                                                        
                        if (tradeSignal.comment == 'Long' || tradeSignal.comment == 'Short') { 
                            placeTradeFuture(strBody);
                            return;
                        }
                    }
                        
                    	
                    
                } else {
                	// Second tarde is null
                	//List<String> secondTradeParts = secondTradeData.split('-');
                    if (firstTradeParts[0] == tradeSignal.side) {
                        req.setBody(jsonBody);
            
                        HTTPResponse res = http.send(req);
                        
                        if (res.getStatusCode() == 201) {
                            // Parse the response to get the trade ID
                            Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
                            Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
                            String tradeId = (String) orderFillTransaction.get('id');
                            Decimal accountBalance = Decimal.valueOf(String.valueOf(orderFillTransaction.get('accountBalance')));
                            String timeStr = String.valueOf(orderFillTransaction.get('time'));
                            timeStr = timeStr.substring(0, timeStr.length() - 1);
                            timeStr = timeStr.substring(0, timeStr.indexOf('.'));
                            timeStr = timeStr.replace('T', ' ');
            
                             
                            Datetime startDateTime =  Datetime.valueOf(timeStr);
                            String index = accFirst.Id + '-' + accFirst.Oanda_Account_Id__c + '-' + tradeId;
                
                            accFirst.Second_Trade__c = tradeSignal.side + '-' + tradeId;
                            update accFirst;
                            
                            Algo_Trade__c tradeInsert = new Algo_Trade__c();
                            tradeInsert.Trading_Account__c = accFirst.Id;
                            tradeInsert.Open_Date_Time__c = startDateTime;
                            tradeInsert.Unique_Id__c = index;
                            tradeInsert.Start_Balance__c = accountBalance;
                            tradeInsert.Trade_Id__c = tradeId;
                            
                            insert tradeInsert;
                        }
                    } else {
                        HTTPResponse res = closeTrade(firstTradeParts[1], '101-004-23424312-002', '3ca1fa8d639245ae65178cdfda22708e-82f12203086ee753781867a146bde7f0');
                        
                        String index = accFirst.Id + '-' + accFirst.Oanda_Account_Id__c + '-' + firstTradeParts[1];
                        accFirst.First_Trade__c = '';
                        update accFirst;
                        
                        Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
                        Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
                        
                        String timeStr = String.valueOf(orderFillTransaction.get('time'));
                        timeStr = timeStr.substring(0, timeStr.length() - 1);
                        timeStr = timeStr.substring(0, timeStr.indexOf('.'));
                        timeStr = timeStr.replace('T', ' ');
            
                             
                        Datetime endDateTime =  Datetime.valueOf(timeStr);
                        //Datetime endDateTime = (Datetime) orderFillTransaction.get('time');
                        
                        Algo_Trade__c algoTrade = [SELECT Id, Trade_ID__c,
                                                          Close_Date_Time__c, Profit__c,
                                                          Profit_Percentage__c, Start_Balance__c
                                                          FROM Algo_Trade__c WHERE Unique_Id__c = :index];
                        Decimal accountBalance = Decimal.valueOf(String.valueOf(orderFillTransaction.get('accountBalance')));
                		Decimal profit = Decimal.valueOf(String.valueOf(orderFillTransaction.get('pl')));
                        Decimal profitPercentage = (profit / algoTrade.Start_Balance__c) * 100;
                        algoTrade.Close_Date_Time__c = endDateTime;
                        algoTrade.Profit__c = profit;
                        algoTrade.Profit_Percentage__c = profitPercentage;
                        
                        update algoTrade;
                        
                        
                        if (tradeSignal.comment == 'Long' || tradeSignal.comment == 'Short') { 
                            placeTradeFuture(strBody);
                            return;
                        }
                    }
                	
                }
                
            } else {
                // Close all trades
                // Add a first new trade -- Checkj
                // 
                
                HTTPResponse res1;
                HTTPResponse res2;
                HTTPResponse res3;
                
                List<String> secondTradeParts = new List<String>();
                List<String> thirdTradeParts = new List<String>();
                
                if (firstTradeData != null) {
                    res1 = closeTrade(firstTradeParts[1], '101-004-23424312-002', '3ca1fa8d639245ae65178cdfda22708e-82f12203086ee753781867a146bde7f0');
                }
                
                if (secondTradeData != null) { 
                    secondTradeParts = secondTradeData.split('-');
                    res2 = closeTrade(secondTradeParts[1], '101-004-23424312-002', '3ca1fa8d639245ae65178cdfda22708e-82f12203086ee753781867a146bde7f0');

                }
                    
                if (thirdTradeData != null) {
                    thirdTradeParts = thirdTradeData.split('-');
                    res3 = closeTrade(thirdTradeParts[1], '101-004-23424312-002', '3ca1fa8d639245ae65178cdfda22708e-82f12203086ee753781867a146bde7f0');

                }
                
                if (firstTradeData != null) {
                    //List<String> firstTradeParts = firstTradeData.split('-');
                
                    String index = accFirst.Id + '-' + accFirst.Oanda_Account_Id__c + '-' + firstTradeParts[1];
                    accFirst.First_Trade__c = '';
                    update accFirst;
                    
                    Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res1.getBody());
                    Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
                    
                    String timeStr = String.valueOf(orderFillTransaction.get('time'));
                    timeStr = timeStr.substring(0, timeStr.length() - 1);
                    timeStr = timeStr.substring(0, timeStr.indexOf('.'));
                    timeStr = timeStr.replace('T', ' ');
        
                         
                    Datetime endDateTime =  Datetime.valueOf(timeStr);
                    //Datetime endDateTime = (Datetime) orderFillTransaction.get('time');
                    
                    Algo_Trade__c algoTrade = [SELECT Id, Trade_ID__c,
                                                      Close_Date_Time__c, Profit__c,
                                                      Profit_Percentage__c, Start_Balance__c
                                                      FROM Algo_Trade__c WHERE Unique_Id__c = :index];
                    Decimal accountBalance = Decimal.valueOf(String.valueOf(orderFillTransaction.get('accountBalance')));
                	Decimal profit = Decimal.valueOf(String.valueOf(orderFillTransaction.get('pl')));
                    Decimal profitPercentage = (profit / algoTrade.Start_Balance__c) * 100;
                    algoTrade.Close_Date_Time__c = endDateTime;
                    algoTrade.Profit__c = profit;
                    algoTrade.Profit_Percentage__c = profitPercentage;
                    
                    update algoTrade;

                }
                if (secondTradeData != null) {
                
                    String index = accFirst.Id + '-' + accFirst.Oanda_Account_Id__c + '-' + secondTradeParts[1];
                    accFirst.Second_Trade__c = '';
                    update accFirst;
                    
                    Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res2.getBody());
                    Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
                    
                    String timeStr = String.valueOf(orderFillTransaction.get('time'));
                    timeStr = timeStr.substring(0, timeStr.length() - 1);
                    timeStr = timeStr.substring(0, timeStr.indexOf('.'));
                    timeStr = timeStr.replace('T', ' ');
        
                         
                    Datetime endDateTime =  Datetime.valueOf(timeStr);
                    //Datetime endDateTime = (Datetime) orderFillTransaction.get('time');
                    
                    Algo_Trade__c algoTrade = [SELECT Id, Trade_ID__c,
                                                      Close_Date_Time__c, Profit__c,
                                                      Profit_Percentage__c, Start_Balance__c
                                                      FROM Algo_Trade__c WHERE Unique_Id__c = :index];
                    Decimal accountBalance = Decimal.valueOf(String.valueOf(orderFillTransaction.get('accountBalance')));
                	Decimal profit = Decimal.valueOf(String.valueOf(orderFillTransaction.get('pl')));
                    Decimal profitPercentage = (profit / algoTrade.Start_Balance__c) * 100;
                    algoTrade.Close_Date_Time__c = endDateTime;
                    algoTrade.Profit__c = profit;
                    algoTrade.Profit_Percentage__c = profitPercentage;
                    
                    update algoTrade;
                }
                
                if (thirdTradeData != null) {
                
                    String index = accFirst.Id + '-' + accFirst.Oanda_Account_Id__c + '-' + thirdTradeParts[1];
                    accFirst.Third_Trade__c = '';
                    update accFirst;
                    
                    Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res3.getBody());
                    Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
                    
                    String timeStr = String.valueOf(orderFillTransaction.get('time'));
                    timeStr = timeStr.substring(0, timeStr.length() - 1);
                    timeStr = timeStr.substring(0, timeStr.indexOf('.'));
                    timeStr = timeStr.replace('T', ' ');
        
                         
                    Datetime endDateTime =  Datetime.valueOf(timeStr);
                    //Datetime endDateTime = (Datetime) orderFillTransaction.get('time');
                    
                    Algo_Trade__c algoTrade = [SELECT Id, Trade_ID__c,
                                                      Close_Date_Time__c, Profit__c,
                                                      Profit_Percentage__c, Start_Balance__c
                                                      FROM Algo_Trade__c WHERE Unique_Id__c = :index];
                    Decimal accountBalance = Decimal.valueOf(String.valueOf(orderFillTransaction.get('accountBalance')));
                	Decimal profit = Decimal.valueOf(String.valueOf(orderFillTransaction.get('pl')));
                    Decimal profitPercentage = (profit / algoTrade.Start_Balance__c) * 100;
                    algoTrade.Close_Date_Time__c = endDateTime;
                    algoTrade.Profit__c = profit;
                    algoTrade.Profit_Percentage__c = profitPercentage;
                    
                    update algoTrade;
                }
                
                                    
                if (tradeSignal.comment == 'Long' || tradeSignal.comment == 'Short') { 
                    placeTradeFuture(strBody);
                    return;
                }
                
                
                
                
            }
        } else {
            // Place first trade
            req.setBody(jsonBody);
            
            HTTPResponse res = http.send(req);
            
            if (res.getStatusCode() == 201) {
                // Parse the response to get the trade ID
                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
                Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
                String tradeId = (String) orderFillTransaction.get('id');
                Decimal accountBalance = Decimal.valueOf(String.valueOf(orderFillTransaction.get('accountBalance')));
                String timeStr = String.valueOf(orderFillTransaction.get('time'));
                timeStr = timeStr.substring(0, timeStr.length() - 1);
                timeStr = timeStr.substring(0, timeStr.indexOf('.'));
                timeStr = timeStr.replace('T', ' ');

                 
                Datetime startDateTime =  Datetime.valueOf(timeStr);
                String index = accFirst.Id + '-' + accFirst.Oanda_Account_Id__c + '-' + tradeId;
    
                accFirst.First_Trade__c = tradeSignal.side + '-' + tradeId;
                update accFirst;
                
                Algo_Trade__c tradeInsert = new Algo_Trade__c();
                tradeInsert.Trading_Account__c = accFirst.Id;
                tradeInsert.Open_Date_Time__c = startDateTime;
                tradeInsert.Unique_Id__c = index;
                tradeInsert.Start_Balance__c = accountBalance;
                tradeInsert.Trade_Id__c = tradeId;
                
                insert tradeInsert;
            }
        }
        

        


        System.debug('REQ | ' + req + ' BODY ' + jsonBody);

        Account acc = [Select Id, Second_SS__c, Oanda_Account_Id__c FROM Account Where Id  ='0017Q00001TwBUCQA3'];
		
        

        System.debug('HERE ' +acc.Second_SS__c);
        
        /**
         * If secondss is filled and comment is long or short, close trade and then place new
         */

        /*if (acc.Second_SS__c == null) {
            //Http http = new Http();
            //HTTPResponse res = http.send(req);
    
            if (res.getStatusCode() == 201) {
                // Parse the response to get the trade ID
                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
                Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
                String tradeId = (String) orderFillTransaction.get('id');
                Decimal accountBalance = Decimal.valueOf(String.valueOf(orderFillTransaction.get('accountBalance')));
                String timeStr = String.valueOf(orderFillTransaction.get('time'));
                timeStr = timeStr.substring(0, timeStr.length() - 1);
                timeStr = timeStr.substring(0, timeStr.indexOf('.'));
                timeStr = timeStr.replace('T', ' ');

                 
                Datetime startDateTime =  Datetime.valueOf(timeStr);
                String index = acc.Id + '-' + acc.Oanda_Account_Id__c + '-' + tradeId;
    
                acc.Second_SS__c = tradeId;
                update acc;
                
                Algo_Trade__c tradeInsert = new Algo_Trade__c();
                tradeInsert.Trading_Account__c = acc.Id;
                tradeInsert.Open_Date_Time__c = startDateTime;
                tradeInsert.Unique_Id__c = index;
                tradeInsert.Start_Balance__c = accountBalance;
                tradeInsert.Trade_Id__c = tradeId;
                
                insert tradeInsert;
                /*Algorithmic_Trade__x tradeInsert = new Algorithmic_Trade__x();
                tradeInsert.Account__c = acc.Id;
                tradeInsert.Open_Date_Time__c = startDateTime;
                tradeInsert.ExternalId = index;
                tradeInsert.Unique_Id__c = index;
                tradeInsert.Start_Balance__c = accountBalance;
                tradeInsert.Trade_Id__c = tradeId;
                
                //QueueableInsertDynamo job = new QueueableInsertDynamo(tradeInsert, 'insert');
        		//System.enqueueJob(job);
            } else {
                System.debug('Failed to place trade: ' + res.getBody());
            }
        } else {
            
            
            
            
            HTTPResponse res = closeTrade(acc.Second_SS__c, '101-004-23424312-002', '3ca1fa8d639245ae65178cdfda22708e-82f12203086ee753781867a146bde7f0');
            String index = acc.Id + '-' + acc.Oanda_Account_Id__c + '-' + acc.Second_SS__c;
            acc.Second_SS__c = '';
            update acc;
            
            Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
            Map<String, Object> orderFillTransaction = (Map<String, Object>) responseMap.get('orderFillTransaction');
            
            String timeStr = String.valueOf(orderFillTransaction.get('time'));
            timeStr = timeStr.substring(0, timeStr.length() - 1);
            timeStr = timeStr.substring(0, timeStr.indexOf('.'));
            timeStr = timeStr.replace('T', ' ');

                 
            Datetime endDateTime =  Datetime.valueOf(timeStr);
            //Datetime endDateTime = (Datetime) orderFillTransaction.get('time');
            
            Algo_Trade__c algoTrade = [SELECT Id, Trade_ID__c,
                                              Close_Date_Time__c, Profit__c,
                                              Profit_Percentage__c, Start_Balance__c
                                              FROM Algo_Trade__c WHERE Unique_Id__c = :index];
            Decimal accountBalance = Decimal.valueOf(String.valueOf(orderFillTransaction.get('accountBalance')));
            Decimal profit = accountBalance - algoTrade.Start_Balance__c;
            Decimal profitPercentage = (profit / algoTrade.Start_Balance__c) * 100;
            algoTrade.Close_Date_Time__c = endDateTime;
            algoTrade.Profit__c = profit;
            algoTrade.Profit_Percentage__c = profitPercentage;
            
            update algoTrade;
            
            if (tradeSignal.comment == 'Long' || tradeSignal.comment == 'Short') {
                /*HTTPResponse res = closeTrade(acc.Second_SS__c, '101-004-23424312-002', '3ca1fa8d639245ae65178cdfda22708e-82f12203086ee753781867a146bde7f0');
                String index = acc.Id + '-' + acc.Oanda_Account_Id__c + '-' + acc.Second_SS__c;
                acc.Second_SS__c = '';
                update acc;
                
                placeTradeFuture(strBody);
                return;
            }
            
            /*Algorithmic_Trade__x algoTrade = [SELECT Id, Trade_ID__c,
                                              Close_Date_Time__c, Profit__c,
                                              Profit_Percentage__c, Start_Balance__c
                                              FROM Algorithmic_Trade__x WHERE Unique_Id__c = :index];
            Decimal accountBalance = (Decimal) orderFillTransaction.get('accountBalance');
            Decimal profit = accountBalance - algoTrade.Start_Balance__c;
            Decimal profitPercentage = (profit / algoTrade.Start_Balance__c) * 100;
            algoTrade.Close_Date_Time__c = endDateTime;
            algoTrade.Profit__c = profit;
            algoTrade.Profit_Percentage__c = profitPercentage;

            //QueueableInsertDynamo job = new QueueableInsertDynamo(algoTrade, 'update');
        	//System.enqueueJob(job);
            //Database.updateImmediate(algoTrade);
            //elapseTime  

            return;
            
        }*/
    }


    private class SignalTrade {
        String side;
        Decimal price;
        Integer contracts;
        String comment;
    }
}