force-app/main/default/objects/Primary_Trade_Link__c/fields/Child_SR_Hedge__c.field-meta.xml
<CustomField>
    <fullName>Child_SR_Hedge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child SR Hedge</label>
    <referenceTo>SR_Hedge__c</referenceTo>
    <relationshipLabel>Primary Trade Link</relationshipLabel>
    <relationshipName>Primary_Trade_Links_Child</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Trade_Link__c/fields/Primary_SR_Hedge__c.field-meta.xml
<CustomField>
    <fullName>Primary_SR_Hedge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary SR Hedge</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SR_Hedge__c.Symbol__c</field>
            <operation>equals</operation>
            <valueField>SR_Hedge__c.Symbol__c</valueField>
        </filterItems>
        <filterItems>
            <field>SR_Hedge__c.Primary_Trade__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SR_Hedge__c</referenceTo>
    <relationshipLabel>Primary Trade Links (Child Trades)</relationshipLabel>
    <relationshipName>Primary_Trade_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/SR_Hedge__c.object-meta.xml
<CustomObject>
    <label>Hedge Trade</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>SR Hedge</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hedge Trades</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/PrimaryLinkService.cls
public with sharing class PrimaryLinkService {
    public static void deletePrimaryLinks(List<SR_Hedge__c> listOfTrades) {
        Set<Id> tradeIds = new Set<Id>();

        for (SR_Hedge__c trade : listOfTrades) {
            tradeIds.add(trade.Id);
        }

        List<Primary_Trade_Link__c> primaryLinksToDelete = [SELECT Id
            FROM Primary_Trade_Link__c
            WHERE Primary_SR_Hedge__c IN :tradeIds OR Child_SR_Hedge__c IN :tradeIds];

        if (!primaryLinksToDelete.isEmpty()) {
            try {
                //System.debug('DELETE ' + primaryLinksToDelete);

                //delete primaryLinksToDelete;
            } catch (Exception ex) {
                System.debug('Error deleting links');
            }
        }

    }
}