force-app/main/default/objects/SR_Hedge__c/SR_Hedge__c.object-meta.xml
<CustomObject>
    <label>Hedge Trade</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>SR Hedge</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hedge Trades</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SR_Hedge__c/fields/Breakeven_Price__c.field-meta.xml
<CustomField>
    <fullName>Breakeven_Price__c</fullName>
    <label>Breakeven Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/Pip_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pip_Amount__c</fullName>
    <label>Pip Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/X1st_Trade_Open_Price__c.field-meta.xml
<CustomField>
    <fullName>X1st_Trade_Open_Price__c</fullName>
    <label>Trade Open Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/X1st_Trade_Units__c.field-meta.xml
<CustomField>
    <fullName>X1st_Trade_Units__c</fullName>
    <label>Trade Units</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/X2nd_Trade_Open_Price__c.field-meta.xml
<CustomField>
    <fullName>X2nd_Trade_Open_Price__c</fullName>
    <label>2nd Trade Open Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SR_Hedge__c/fields/X2nd_Trade_Units__c.field-meta.xml
<CustomField>
    <fullName>X2nd_Trade_Units__c</fullName>
    <label>2nd Trade Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CalculateBreakeven.cls
public class CalculateBreakeven {

    @InvocableMethod(label='Calculate Breakeven 2 Trade' description='Calculate BE Price')
    public static List<SR_Hedge__c> calculate(List<SR_Hedge__c> inputList) {
        SR_Hedge__c currentTrade = inputList.get(0);
        
        Double currentPrice = currentTrade.X2nd_Trade_Open_Price__c;
        Double currentProfit = calculateProfit2Trade(currentPrice,
                                                    currentTrade.X1st_Trade_Open_Price__c,
                                                    currentTrade.X2nd_Trade_Open_Price__c,
                                                    currentTrade.X1st_Trade_Units__c,
                                                    currentTrade.X2nd_Trade_Units__c);
        while(currentProfit < 0) {
            currentPrice += currentTrade.Pip_Amount__c;
            currentProfit = calculateProfit2Trade(currentPrice,
                                                    currentTrade.X1st_Trade_Open_Price__c,
                                                    currentTrade.X2nd_Trade_Open_Price__c,
                                                    currentTrade.X1st_Trade_Units__c,
                                                    currentTrade.X2nd_Trade_Units__c);
        }
        
        
        currentTrade.Breakeven_Price__c = currentPrice;
        
        List<SR_Hedge__c> newList = new List<SR_Hedge__c>();
        newList.add(currentTrade);
        return newList;
    } 
    
    public static Double calculateProfit2Trade(Double cP, Decimal openOne, Decimal openTwo, Decimal unitOne, Decimal unitTwo) {
        return ((cP - openOne) * unitOne) + ((cP - openTwo) * unitTwo);
    }
}